apiVersion: v1
kind: Secret
metadata:
  name:  daniellacos.se-tls
data:
  tls.crt: ''
  tls.key: ''
type: kubernetes.io/tls
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: daniellacos.se-proxy
spec:
  tls:
    - hosts:
      - daniellacos.se
      secretName: daniellacos.se-tls
  rules:
  - http:
      host: daniellacos.se
      paths:
      - path: /*
        backend:
          serviceName: daniellacos.se-proxy
          servicePort: 8080
      - path: /slots/*
        backend:
          serviceName: idea-slot-machine
          servicePort: 8080
---
